CREATE TABLE IF NOT EXISTS "Goal" (
    "id" SERIAL PRIMARY KEY,
    "title" TEXT NOT NULL,
    "progress" INTEGER NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL DEFAULT 'Đang thực hiện',
    "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);